Added ability for changing VPN subnet
jpetazzo/dockvpn pull request #41
Opened 2021-12-03 09:08 UTC by AlekseySpiridonov

Added ability for changing VPN subnet for avoiding conflicts with local networks.  
By default is using `192.168.255.0/24` but it can be overdid by `SUBNET` var.

2023-09-15 09:57 UTC, coolOpenSourceDev commented
@jpetazzo 
Could you please review this change? 
I use several VPN instances and connect them to one of my routers. Without the ability to change subnets on routers, an address conflict occurs. The ability to change subnets could solve this problem.

2023-09-15 10:04 UTC, tphillips requested changes
SUBNET vs. VPN_SUBNET variable name. 

A default value would be good if possible?

2023-09-15 13:27 UTC, AlekseySpiridonov commented
@tphillips 
I am sorry, but it looks like I didn't get you.

**Do you suggest using only one BASH variable?** And what should it be called?

**Note:**
Right now we have the environment variable `SUBNET` with the default value `192.168.255`. This variable can be set via the command line. In BASH script, we use the default or overridden value of the `SUBNET` environment variable in the `VPN_SUBNET` BASH variable.

2023-09-18 16:09 UTC, 1vanSmirnov commented
Subnet changes for VPN will be a valuable contribution. (Default subnet, in my case, is interferred with a local subnet - not convenient at all)

2023-11-01 13:15 UTC, coolOpenSourceDev commented
@jpetazzo 
Please forgive me for the direct question, but are there any plans to review this functionality or is the repository frozen after the commit [6e9c6ea](https://github.com/jpetazzo/dockvpn/commit/6e9c6ea2cb5e8ab58c0c471d91f1f0108a01e09e)?
The ability to change subnets is very important for my needs.

2023-11-06 18:42 UTC, jpetazzo commented
Hi @coolOpenSourceDev ! This is a very valid question. I admit that I don't maintain these projects very thoroughly (because they were initially just meant to be proof of concepts and cool demos; and it always surprises me when I see people using this - or other stuff like pipework - extensively😅)

However I see that this is a fairly straightforward pull request, so I'm going to take a look now, maybe just reword a tiny bit the doc and ship it.

Huge thanks for @AlekseySpiridonov for the PR. I'm very sorry that it took me so long to get to that.

OK, I'm going to review+merge now, hoping I don't get interrupted in the middle 😅

2023-11-06 18:48 UTC, merged

2023-11-06 18:48 UTC, jpetazzo commented
Done! Thanks again everyone <3

2023-11-07 15:15 UTC, coolOpenSourceDev commented
Thanks a lot!
I really need this change. Thank you for review.